### ISSUE TITLE
Add some theming

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/zoo-grommet#1]
The current theme just inherits entirely from the default theme. There are some theme examples available in the grommet repo, we just need to start copying our own styles in.

The style guide is available at https://github.com/zooniverse/Brand/blob/master/style%20guide/styleguide-classify.pdf

**Comment by mcbouslog** [comment]
started with colors, [compare branch `zoo-theme`](https://github.com/zooniverse/zoo-grommet/compare/zoo-theme).

based on https://grommet.github.io/docs/color/ and [Zooniverse Style Guide](https://github.com/zooniverse/Brand/blob/master/style%20guide/style%20guide/Style%20Guide%20%7C%20Colors%2C%20Buttons%2C%20Type.png) from [Brand](https://github.com/zooniverse/Brand) repo. styleguide-classify PDF linked above includes colors slightly off from general style guide, and per discussion with @beckyrother we thought we'd start based on the general style guide, but also used a few from the classify style guide to utilize as many of the Grommet variables as possible.

eventually we'll want to note (in the General Style Guide?) what Grommet color variable (brand, accent-1, accent-2, neutral-1, grey-1, light-1, etc.) is associated with the Zooniverse colors, but not necessary until the Zooniverse Grommet Theme is farther along.

**Comment by mcbouslog** [comment]
custom Grommet themes for reference:
- https://github.com/grommet/grommet/blob/master/src/scss/aruba/_aruba.defaults.scss
- https://github.com/grommet/grommet/blob/master/src/scss/vanilla/_vanilla.defaults.scss
- https://github.com/grommet/grommet/blob/master/src/scss/hpe/_hpe.defaults.scss

**Comment by mcbouslog** [comment]
tried font without luck.
```
@import url(https://fonts.googleapis.com/css?family=Karla);

$brand-font-family: 'Karla', Arial, sans-serif;
$brand-large-number-font-family: 'Karla', Arial, sans-serif;
$text-font-weight: 400;
$text-strong-font-weight: 700;

.test-font {
  font-family: 'Karla', sans-serif;
}
```

but my `test-font` class works as expected. will revisit...
