### ISSUE TITLE
Including font into the project

### ISSUE THREAD

**Issue by nnurmano** [zooniverse/zoo-grommet#5]
I am following your instruction to adding a new font (Karla) and I would like to clear some steps.
In https://fonts.google.com/specimen/Karla?selection.family=Karla, it is only given 
<link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
or 
<style>
@import url('https://fonts.googleapis.com/css?family=Karla');
</style>,
Q1. In your file you quote https://fonts.gstatic.com instead, but Google is given https://fonts.googleapis.com end point. Could you elaborate on this step?
Q2. When downloading from https://fonts.googleapis.com, we are only given ttf fonts, but you use woff2, do we have to take an extra step to converting to woff2?

**Comment by srallen** [comment]
@nomadus If you open in the browser the urls, for example https://fonts.googleapis.com/css?family=Karla, provided to you by google from either the link source or from the import, you will see some static CSS generated by Google with the font-face declarations. Just copy and paste this for the google font you wish to use into your own theme sass file.

I'm not sure what your options are for downloaded versions of free google fonts. You may want to take a look at the documentation of the font you're downloading.
